### ISSUE TITLE
401 code 0

### ISSUE THREAD

**Issue by MuttMelter** [abbydiode/UndiscordPlus#8]
Hi i have same problem w previuos version undiscord
i was able to delete like 20k poss 30k messages then it just wont let me anymore 
how can i fix this
![Screenshot (224)](https://user-images.githubusercontent.com/82054663/155735301-12e00c9f-21ff-4882-954b-af2ff33b98dc.png)

**Comment by abbydiode** [comment]
Just experienced this issue myself, problem was that Chrome had auto-filled my Discord password in the Authorization textbox. Make sure you click `Get` next to Authorization to make sure it uses the right token for auth.
